name = "HeatFlow"
version = "0.5.0"
license = "GPLv3"
author = "HeatFlow maintainers"
maintainer = ""
description = "A Fortran executable for modelling Cattaneo heat flow"

[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]

[dependencies]
mpi = "*"

[features]
petsc.build.external-modules = ["petscksp"]
petsc.build.link = ["petsc"]

[profiles]
default = ["petsc"]

[library]
source-dir="src"

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[[executable]]
name="HeatFlow"
source-dir="src"
main="heatflow.f90"
